apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocici-backend
  labels: 
    app.kubernetes.io/name: cici
    app.kubernetes.io/instance: cici
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cici
      app.kubernetes.io/instance: cici
  replicas: 1
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: cici
        app.kubernetes.io/instance: cici
    spec:
      containers:
        - name: hellocici-backend
          image: {{ .Values.ciciBackend.image.repository }}:{{ .Values.ciciBackend.image.tag }}
          imagePullPolicy: Always 
          command:
            - /workspace/cici
          ports:
            - protocol: TCP
              containerPort: 20219
      imagePullSecrets:
        - name: hello-candidate-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hellocici-backend
  labels:
    app.kubernetes.io/name: cici
    app.kubernetes.io/instance: cici
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: 20219
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: cici-index
#   annotations:
#     "helm.sh/resource-policy": keep
#     nginx.ingress.kubernetes.io/proxy-body-size: 100m
# spec:
#   rules:
#   - host: {{.cici_host}}
#     http:
#       paths:
#       - path: /welcome
#         backend:
#           serviceName: hellocici-backend
#           servicePort: 8090
     