apiVersion: apps/v1
kind: Deployment
metadata:
  name: cici-frontend
  labels:
    app.kubernetes.io/instance: cici-frontend
    app.kubernetes.io/name: cici
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cici-frontend
      app.kubernetes.io/name: cici
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cici-frontend
        app.kubernetes.io/name: cici
    spec:
      containers:
        - name: cici-frontend
          image: ccr.ccs.tencentyun.com/koderover-public/cici-frontend:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100M


