apiVersion: v1
kind: Service
metadata:
  name: cici-frontend
  labels:
    app.kubernetes.io/instance: cici-frontend
    app.kubernetes.io/name: cici
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80