apiVersion: v1
kind: Service
metadata:
  name: cici-backend
  labels:
    app.kubernetes.io/name: cici
    app.kubernetes.io/instance: cici-backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 20219
      targetPort: 20219